Update compute-version-and-create-empty-release.yml

diff --git a/.github/workflows/compute-version-and-create-empty-release.yml b/.github/workflows/compute-version-and-create-empty-release.yml
--- a/.github/workflows/compute-version-and-create-empty-release.yml
+++ b/.github/workflows/compute-version-and-create-empty-release.yml
@@ -30,8 +30,11 @@ jobs:
           echo "Detected last version: \"$LATEST_TAG\""
           if [[ "$LATEST_TAG" =~ ^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(-((0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(\.(0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(\+([0-9a-zA-Z-]+(\.[0-9a-zA-Z-]+)*))?$ ]]; then
             MAJOR="${match[1]}"
+            [[ -n "$MAJOR" ]] || echo "Unable to compute the major version" && false
             MINOR="${match[2]}"
+            [[ -n "$MINOR" ]] || echo "Unable to compute the minor version" && false
             PATCH="${match[3]}"
+            [[ -n "$PATCH" ]] || echo "Unable to compute the patch version" && false
             case "${{ inputs.update-version }}" in
               major)
                 COMMIT_COUNT_FROM_TAG="$(git rev-list HEAD --count || echo 1)"
